# Generated by Django 5.0.6 on 2024-07-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_App', '0002_address_food_items_orders_staff_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
