# Generated by Django 5.0.6 on 2024-07-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_App', '0004_rename_phone_number_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_items',
            name='item_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
